'use strict';mix_d("MonarchShoppingCXFeedbackWidgetCards__shopping-cx-feedback-widget:shopping-cx-feedback-widget__gEAolcYS","exports tslib @c/logger @c/metrics @c/pagemarker @c/scoped-dom @c/remote-operations".split(" "),function(w,u,C,m,D,E,F){function f(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var k=f(C),G=f(D),e=f(E),H=f(F),p=function(){return H["default"].setup()},I={CREDIT_CARD_NUMBER:[/\b\d{15,16}\b/i,/\b\d{4}([\- ])\d{4}\1\d{4}\1\d{4}\b/i],PASSPORT:[/\b[Cc\d]\d{8}\b/i],
ADDRESS:[/\d{1,5}\s([\w\.\-]+\s){1,3}(st|ln|rd|ave|dr|pl|pkwy|blvd|street|lane|road|avenue|drive|parkway|boulevard)\b/i],PHONE_NUMBER:[/\b(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?\b/g],EMAIL:[/[a-z0-9!#$%&'*+\/=?\^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?\^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/i]},
J={NA:{CREDIT_CARD_NUMBER:[/\b\d{4}([\- ])\d{6}\1\d{5}\b/i],NATIONAL_IDENTIFIER:[/\b(?!000)\d{3}[\- ](?!00)\d{2}[\- ](?!0000)\d{4}\b/i,/\b\d{2}[\- ]\d{7}\b/i],PASSPORT:[/\b[A-z]{2}[0-9]{7}\b/i],ADDRESS:[/\b\d{5}[ \-]\d{4}\b/,/\b(?:[ABCEGHJ-NPRSTVXY]\d[A-Z][ -]?\d[A-Z]\d)\b/i],PHONE_NUMBER:[/\b(?:\+\d{1,3}[\( \-\/\-])?(?:\d{3}|\(\d{3}\))([ -\/\.])\d{3}([\-\/\.])\d{4}\s*((x|ex\w*|#)\s*\d+)?\b/g]},EU:{CREDIT_CARD_NUMBER:[],NATIONAL_IDENTIFIER:[],PASSPORT:[/\b[A-z][0-9]{6}\b/i,/\b[A-z]{2}[0-9]{7}\b/i,
/\b[A-z0-9][0-9]{7}\b/i,/\b[CFGHJK0-9][0-9]{3}[CHJKLMNPRTVWXYZ0-9]{5}[0-9]\b/i,/\b[A-z][0-9]{6,7}\b/i,/\b[0-9]{12}\b/i,/\b[0-9]{2}[A-z]{2}[0-9]{5}\b/i,/\b[A-z] ?[0-9]{7}\b/i],ADDRESS:[/\b(?:[0-8]\d|9[0-8])\d{3}\b/i,/\b\d{5}\b/i,/\b(?:NL-)?(?:[1-9]\d{3} ?(?:[A-EGHJ-NPRTVWXZ][A-EGHJ-NPRSTVWXZ]|S[BCEGHJ-NPRTVWXZ]))\b/i,/\b(?:0[1-9]|[1-4]\d|5[0-2])\d{3}\b/,/\b[1-9]\d{3}\b/,/\b(?:GIR 0AA|(?:(?:(?:A[BL]|B[ABDHLNRSTX]?|C[ABFHMORTVW]|D[ADEGHLNTY]|E[HNX]?|F[KY]|G[LUY]?|H[ADGPRSUX]|I[GMPV]|JE|K[ATWY]|L[ADELNSU]?|M[EKL]?|N[EGNPRW]?|O[LX]|P[AEHLOR]|R[GHM]|S[AEGK-PRSTY]?|T[ADFNQRSW]|UB|W[ADFNRSV]|YO|ZE)[1-9]?\d|(?:(?:E|N|NW|SE|SW|W)1|EC[1-4]|WC[12])[A-HJKMNPR-Y]|(?:SW|W)(?:[2-9]|[1-9]\d)|EC[1-9]\d)\d[ABD-HJLNP-UW-Z]{2}))\b/i],
PHONE_NUMBER:[/(\+|\b011\W*)(9[976]\d|8[987530]\d|6[987]\d|5[90]\d|42\d|3[875]\d|2[98654321]\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7)(\W*\d){1,14}\b/i]},FE:{CREDIT_CARD_NUMBER:[],NATIONAL_IDENTIFIER:[],PASSPORT:[/\b[Cc\d]\d{8}\b/i],ADDRESS:[/\b(?:(?:[2-8]\d|9[0-7]|0?[28]|0?9(?=09))(?:\d{2}))\b/i,/\b\d{3}-\d{4}\b/],PHONE_NUMBER:[/(\+|\b011\W*)(9[976]\d|8[987530]\d|6[987]\d|5[90]\d|42\d|3[875]\d|2[98654321]\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7)(\W*\d){1,14}\b/i]}},
K={ABUSE_WORD:[/\bsh[i|*|1]t\b|\bf[u|*][c|*]k\b|\bb[i|*]tch\b|\bcrap\b|\bsucks\b|\bdamn\b|\bwhore\b|\bass\b|\\s/ig]},c;(function(a){a.NA="NA";a.FE="FE";a.EU="EU"})(c||(c={}));var x;(x||(x={})).PNG="png";var v=function(a,b,c){var e,d,l=b.violationMap;b=b.textAfterValidation;for(var g in a){var L=a[g];try{for(var k=(e=void 0,u.__values(L)),n=k.next();!n.done;n=k.next()){var h=b.match(n.value);h&&(h="CREDIT_CARD_NUMBER"===g?h.filter(Boolean).filter(M):h.filter(Boolean),0<h.length&&(c?b=b.replace(new RegExp("\\b"+
h.join("\\b|\\b")+"\\b","gi"),""):l[g]?l[g]=l[g].concat(h):l[g]=h))}}catch(N){e={error:N}}finally{try{n&&!n.done&&(d=k.return)&&d.call(k)}finally{if(e)throw e.error;}}}return{textAfterValidation:b,violationMap:l}},M=function(a){if(/[^0-9\-\s]+/.test(a))return!1;var b=0,c=!1;a=a.replace(/\D/g,"");if(""===a)return!1;for(var e=a.length-1;0<=e;e--){var d=a.charAt(e);d=parseInt(d,10);c&&(d*=2,9<d&&(d-=9));b+=d;c=!c}return 0===b%10},q;(function(a){a.Rating="Rating";a.Text="Text"})(q||(q={}));var P=function(){var a=
e["default"].cardRoot.getElementsByClassName("shoppingCxFeedbackRootWidget")[0];a&&p().getRatingFeedbackHtml().then(function(b){b&&b.outerHTML&&(a.innerHTML=b.outerHTML,O())}).catch(function(a){k["default"].log("Experiencing some issues to load heimdall feedback widget rating view, trace: "+a,"ERROR")})},O=function(){var a=e["default"].cardRoot.getElementsByClassName("_shopping-cx-feedback-widget_style_shopping-cx-feedback-widget__3OJWU")[0],b=e["default"].cardRoot.getElementsByClassName("widgetContentContainer")[0],
l=e["default"].cardRoot.getElementsByClassName("feedbackRadioHeading")[0],y=e["default"].cardRoot.getElementsByClassName("feedbackRadioButton");a&&m.count("shoppingcxWidgetGlanceView",1);for(var d=function(a){var d=y[a].getElementsByTagName("input")[0];d&&(d.addEventListener("click",function(){d.disabled=!0;m.count("ratingFeedbackSubmitted",1);var a=Number(d.value);Q(a,l.textContent);p().getTextFeedbackHtml().then(function(d){b&&(b.innerHTML=d.outerHTML);d=e["default"].cardRoot.getElementsByClassName("_shopping-cx-feedback-widget_style_text-feedback-submit-button__OfIRR")[0];
var h=e["default"].cardRoot.getElementsByTagName("textarea")[0],g=e["default"].cardRoot.getElementsByClassName("_shopping-cx-feedback-widget_style_text-feedback-alert-info__iTrz-")[0];if(d&&h){var f=!1;d.addEventListener("click",function(){m.count("textFeedbackSubmitted",1);f&&(r(!1),f=!1);var b=h.value,d=l.textContent,g=e["default"].cardRoot.getElementsByClassName("mkpID")[0];g=J[{ATVPDKIKX0DER:c.NA,A2EUQ1WTGCTBG2:c.NA,A1AM78C64UM0Y8:c.NA,A39IBJ37TRP1C6:c.FE,AD2EMQ3L3PG8S:c.FE,A1VC38T7YXB528:c.FE,
A19VAU5U5O7RUS:c.FE,A1F83G8C2ARO7P:c.EU,A1PA6795UKMFR9:c.EU,A13V1IB3VIYZZH:c.EU,APJ6JRA9NG5V4:c.EU,A1RKKUPIHCS9HS:c.EU,ARBP9OOSHTCHU:c.EU,A21TJRUUN4KGV:c.EU,A1805IZSGTT6HS:c.EU,A2VIGQ35RCS4UG:c.EU,A17E79C6D8DWNP:c.EU,A33AVAJ2PDY3EV:c.EU,A1C3SOZRARQ6R3:c.EU,A2NODRKZP88ZB9:c.EU}[g.value]];b={textAfterValidation:b,violationMap:{}};b=v(K,b,!0);b=v(I,b,!1);g&&(b=v(g,b,!1));g=b.violationMap;if(0<Object.keys(g).length)k["default"].log("Feedback validation: "+Object.keys(g).toString(),"WARN"),z(!1),m.count("textFeedbackFailedValidation",
1);else{b=b.textAfterValidation;d={feedbackType:q.Text,feedbackContentIntValue:a,feedbackContentString:encodeURIComponent(b),feedbackQuestion:encodeURIComponent(d)};A(d);if(d=e["default"].cardRoot.getElementsByClassName("_shopping-cx-feedback-widget_style_text-feedback-submit-button__OfIRR")[0])d.getElementsByTagName("input")[0].disabled=!0;B()}});h.addEventListener("input",function(){g&&"none"===g.style.display&&z(!0);h.value&&0<h.value.length&&!f&&(r(!0),f=!0);h.value&&0<h.value.length||!f||(r(!1),
f=!1)})}}).catch(function(a){k["default"].log("Experiencing some issues redricting to text feedback page, trace: "+a,"ERROR");B()})}),d.checked&&d.click())},f=0;f<y.length;f++)d(f);(d=e["default"].cardRoot.getElementsByClassName("_shopping-cx-feedback-widget_style_close__2J0I_")[0])&&d.addEventListener("click",function(){m.count("shoppingcxWidgetDismissed",1);r(!1);a&&(p().postWidgetDismissed().then(function(a){a.succeed||k["default"].log("Experiencing some service side issues when calling submitFeedback api with dismiss action: "+
a.message,"ERROR")}).catch(function(a){k["default"].log("Experiencing some client side issues when calling submitFeedback api with dismiss action, trace: "+a,"ERROR")}),t(a))})},Q=function(a,b){a={feedbackType:q.Rating,feedbackContentIntValue:a,feedbackQuestion:encodeURIComponent(b)};A(a)},A=function(a){p().postFeedbackData(a).then(function(a){a.succeed||k["default"].log("Experiencing some service side issues when calling submitFeedback api: "+a.message,"ERROR")}).catch(function(a){k["default"].log("Experiencing some client side issues when calling submitFeedback api, trace: "+
a,"ERROR")})},t=function(a){a.style.display="none"},z=function(a){var b=e["default"].cardRoot.getElementsByClassName("_shopping-cx-feedback-widget_style_text-feedback-alert-info__iTrz-")[0],c=e["default"].cardRoot.getElementsByClassName("_shopping-cx-feedback-widget_style_text-feedback-alert-error__1Y0pJ")[0],f=a?b:c;a=a?c:b;f&&a&&"none"!==a.style.display&&(t(a),f.style.display="inline-block")},r=function(a){window.onbeforeunload=a?function(a){a.preventDefault();a.returnValue=""}:null},B=function(){var a=
e["default"].cardRoot.getElementsByClassName("widgetContentContainer")[0],b=e["default"].cardRoot.getElementsByClassName("_shopping-cx-feedback-widget_style_thank-you-view-placeholder__2G21U")[0],c=e["default"].cardRoot.getElementsByClassName("_shopping-cx-feedback-widget_style_shopping-cx-feedback-widget__3OJWU")[0],f=e["default"].cardRoot.getElementsByClassName("_shopping-cx-feedback-widget_style_close__2J0I_")[0];a&&b&&(a.innerHTML=b.innerHTML);f&&t(f);setTimeout(function(){c&&t(c)},3E3)};w._operationNames=
["getRatingFeedbackHtml","getTextFeedbackHtml","postFeedbackData","postWidgetDismissed"];w.card=function(){return u.__awaiter(void 0,void 0,void 0,function(){return u.__generator(this,function(a){G["default"].pageReady.then(P);return[2]})})}});
